---
apiVersion: v1
kind: Service
metadata:
  namespace: devel
  name: exota-milter
spec:
  selector:
    app: exota-milter
  ports:
    - protocol: TCP
      port: 4321
      targetPort: 4321